sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - ng build --prod --aot --env=prod
install:
  - npm install
before_deploy:
  - openssl aes-256-cbc -K $encrypted_ae389961b42c_key -iv $encrypted_ae389961b42c_iv
    -in id_rsa_fe_travis.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  on:
    branch: release/0.1.0
